name: Test

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: task docker
